name: Continuous Integration

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs: 
  continuous-integration: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.
      - name: Install dependencies and run tests
        run: |
          npm install
          npm test
